name: ${project.artifactId}
main: club.kid7.bannermaker.BannerMaker
version: ${project.version}
author: KID
folia-supported: true
softdepend: [ Vault ]
api-version: 1.21.4
commands:
  BannerMaker:
    description: BannerMaker
    usage: /<command>
    aliases: [ bm ]
    permission: bannermaker.use
    permission-message: Lacking permission <permission>
permissions:
  bannermaker.admin:
    description: Whole permission of BannerMaker
    default: op
    children:
      bannermaker.player: true
      bannermaker.getbanner.free: true
      bannermaker.reload: true
  bannermaker.player:
    description: Permissions for normal players
    default: true
    children:
      bannermaker.use: true
      bannermaker.getbanner: true
      bannermaker.hand: true
      bannermaker.see: true
      bannermaker.view: true
      bannermaker.show: true
  bannermaker.use:
    description: Permission of using BannerMaker
    default: true
  bannermaker.getbanner:
    description: Permission to get banners from BannerMaker
    default: op
  bannermaker.getbanner.complex-craft:
    description: Bypass 6-patterns limit when getting banner (Enabled in config)
    default: op
  bannermaker.getbanner.free:
    description: Bypass fee of get Banner
    default: op
  bannermaker.hand:
    description: View banner info of the banner in hand
    default: true
  bannermaker.see:
    description: View banner info of the banner you're looking at
    default: true
  bannermaker.view:
    description: View banner info of the banner command
    default: true
  bannermaker.show:
    description: Show banner info to players
    default: op
    children:
      bannermaker.show.nearby: true
      bannermaker.show.all: true
      bannermaker.show.receive: true
  bannermaker.show.nearby:
    description: Show banner info to nearby players
    default: op
  bannermaker.show.all:
    description: Show banner info to all players
    default: op
  bannermaker.show.receive:
    description: Receive banner info showing messages from other players
    default: true
  bannermaker.reload:
    description: Permission to reload all config
    default: op
